danielparks/puppet-rustup

REFERENCE.md, lib/puppet/provider/rustup_exec.rb, lib/puppet/provider/rustup_internal/shell.rb, lib/puppet/provider/rustup_toolchain/exec.rb, lib/puppet/type/rustup_internal.rb, lib/puppet/type/rustup_toolchain.rb, manifests/toolchain.pp, spec/unit/puppet/provider/rustup_toolchain/exec_spec.rb, spec/unit/puppet/type/rustup_internal_spec.rb, spec/unit/puppet/type/rustup_toolchain_spec.rb
* Add `ensure => latest` support.
* Autorequires the `rustup` resource.
* Better matching for installed toolchains.
* Refactor provider code into common base class.
=> New rustup_toolchain type/provider

lib/puppet/provider/rustup_internal/shell.rb, lib/puppet/type/rustup_internal.rb, lib/puppet_x/rustup/util.rb, manifests/init.pp, spec/acceptance/user_spec.rb, spec/unit/puppet_x/rustup/util_spec.rb
If the user is removed before `rustup { 'user': ensure => absent }` runs, then it will not be able to run the uninstaller. This manually removes the `. "$HOME/.cargo/env"` line from RC scripts.
=> Ensure changes to shell init scripts are removed

lib/puppet/provider/rustup_exec.rb, lib/puppet/provider/rustup_internal/shell.rb, lib/puppet/provider/rustup_toolchain/exec.rb
I’m sure the performance difference is trivial, especially considering how I use it.
=> Switch to prefered method to call Puppet.debug

CHANGELOG.md, README.md, lib/puppet/provider/rustup_internal/default.rb, spec/acceptance/user_spec.rb
Now supports installing non-host toolchains for use with emulators. For example, it is now possible to install the `x86_64-pc-windows-gnu` toolchain on a Linux host without warnings.
=> Support non-host toolchains

README.md, REFERENCE.md, lib/puppet/provider/rustup_internal/default.rb, lib/puppet/type/rustup_internal.rb, manifests/global/toolchain.pp, manifests/init.pp, manifests/toolchain.pp, spec/acceptance/user_spec.rb, types/profile.pp
This allows the profile to be set when installing toolchains. It only has an effect during the initial install. All it does is decide which components are installed by default.
=> Add profile parameter for toolchains

REFERENCE.md, lib/puppet/provider/rustup_exec.rb, lib/puppet/type/rustup_internal.rb, manifests/global.pp, manifests/init.pp, spec/acceptance/user_spec.rb, spec/unit/puppet/type/rustup_internal_spec.rb
This adds a `dist_server` parameter that can be set to `'https://dev-static.rust-lang.org'` to install pre-release toolchains. This works by setting the `RUSTUP_DIST_SERVER` environment variable.
=> Add option to install pre-release toolchains

README.md, lib/puppet/provider/rustup_exec.rb
This module now outputs the commands being executed (e.g.
`/home/user/.cargo/bin/rustup toolchain install stable`) at the info
logging level (enabled by `--verbose`) when the `RUSTUP_TRACE`
environment variable is set.
It makes it easier to see what’s going on under the hood without
enabling all debugging messages.
=> Option to make tracing rustup commands easier

REFERENCE.md, manifests/exec.pp, manifests/global/target.pp, manifests/target.pp, manifests/toolchain.pp
There seems to be [a bug in puppet strings][] that prevents default values from being outputted correctly in REFERENCE.md. Values of the form `$var.func(...)` would output as `(...)`.
This switches over to the `func($var, ...)` form, though unfortunately I think it is less readable.
[a bug in puppet strings]: https://github.com/puppetlabs/puppet-strings/issues/240
=> Fix default values in REFERENCE.md

CHANGELOG.md, REFERENCE.md, manifests/exec.pp, manifests/global/target.pp, manifests/target.pp, manifests/toolchain.pp
Due to a [bug in Puppet Strings][bug], the default values were being outputted in REFERENCE.md incorrectly. Commit
c3db65ba4ea820e53adf9334bdd4ee245a4b5e03 fixed the problem at the cost of making the default values harder to understand.
I have fixed the bug in Puppet Strings (though it hasn’t been merged and released), so this reverts the aforementioned commit and generates a fresh REFERENCE.md.
[bug]: https://github.com/puppetlabs/puppet-strings/issues/240
=> Switch back to more readable default values

.editorconfig, .pdkignore, .sync.yml, Gemfile
* Add `.editorconfig` since it seems like a good idea. Not sure why it’s off by default.
* Disable github_changelog_generator since we don’t use it.
* Add lint check for legacy facts.
* Don’t bundle fix-reference.rb into the module release.
* Remove spec_helper cconfiguration that didn’t do anything.
=> Miscellaneous PDK configuration updates

.github/workflows/pr-checks.yaml, spec/acceptance/user_spec.rb, spec/spec_helper_acceptance_local.rb
This also makes the acceptance tests usable when not run under vagrant.
=> (#24) Add acceptance tests to PR checks

lib/puppet/provider/rustup_internal/default.rb
Switch to `compact` instead of `reject { |e| e.nil? }`, and combine lines to avoid variable assignment.
=> Trivial clean up in `normalize_toolchain_name`

lib/puppet/provider/rustup_internal/default.rb, lib/puppet/type/rustup_internal.rb, lib/puppet_x/rustup/property/set.rb, lib/puppet_x/rustup/property/subresources.rb, lib/puppet_x/rustup/util.rb
Apparently using `require` within a Puppet module can violate environment isolation, since the puppetserver might search in other environments (or possibly not search at all if it’s cached) for the relevant files.
This doesn’t change file in spec, since those aren’t used within the puppetserver process.
Fixes #35
=> Switch back to require_relative

lib/puppet/provider/rustup_internal/default.rb
Combine checks for `ensure => present` in subresources when the resource itself is absent. This sets us up for managing components.
=> Reduce duplicate code

lib/puppet_x/rustup/property/set.rb, lib/puppet_x/rustup/property/subresources.rb, spec/unit/puppet_x/rustup/property/set_spec.rb, spec/unit/puppet_x/rustup/property/subresources_spec.rb
The identity function is supposed to uniquely identify a subresource in a set for the purpose of detecting defaults. At its most basic, it’s supposed to just just remove the `ensure` attribute and compute the hash so you can’t have two otherwise identical subresources with different values for `ensure`.
Previously it stripped an attribute called `absent` rather than the `ensure` attribute.
Previously, entries in sets were considered to be unchanged if their identities were the same. In particular, it ignored most changes to `ensure`. This adds code to make sure that entries with the same identity are actually unchanged.
This also adds a warning when there’s an error normalizing and deduplicating the `is` array.
=> Fix subresource sync issues

spec/acceptance/user_spec.rb
Previously, running the acceptance tests twice on the same VM or container would cause a couple of test failures. This fixes it, though I’m not entirely sure how, since one of the errors was that the user existed at the beginning of the test… and the tests already deleted the user.
=> Clean up better after individual acceptance tests

lib/puppet/provider/rustup_exec.rb, lib/puppet/provider/rustup_internal/default.rb, lib/puppet/type/rustup_internal.rb, lib/puppet_x/rustup/provider.rb, lib/puppet_x/rustup/provider/subresources.rb, lib/puppet_x/rustup/provider/targets.rb, lib/puppet_x/rustup/provider/toolchains.rb, spec/unit/puppet/provider/rustup_internal/default_spec.rb
This helps separate code managing targets and toolchains out from the general provider.
Fixes #17
=> Move subresource management code into new classes

lib/puppet_x/rustup/property/subresources.rb
When a parameter changes, Puppet displays a change message with the old and new values. Switching to the subresource collection classes on the provider broke this display — the old value was displayed as an opaque ruby object.
This restores the change display to show the interior attributes of all subresourcces.
=> Fix display of changes to subresources

lib/puppet_x/rustup/provider/targets.rb
Use `system` instead of potentially calling out to `list_installed` multiple times when managing targets.
=> Reduce calls to rustup when managing targets

lib/puppet/provider/rustup_internal/default.rb, lib/puppet_x/rustup/property/subresources.rb, lib/puppet_x/rustup/provider/collection.rb, lib/puppet_x/rustup/provider/collection/subresources.rb, lib/puppet_x/rustup/provider/collection/targets.rb, lib/puppet_x/rustup/provider/collection/toolchains.rb
This moves the collection classes from `PuppetX::Rustup::Provider` to `PuppetX::Rustup::Provider::Collection` for clarity. This will be more important if we decide to create classes for subresource objects.
=> Clarify name of collection classes for provider

lib/puppet/provider/rustup_exec.rb
To really verify that rustup is installed, we need to execute it. Assume that as long as it’s a file (or resolves to a file), it’s installed.
=> Remove FIXME: just check that bin/rustup is a file

lib/puppet/type/rustup_internal.rb, lib/puppet_x/rustup/provider/collection/subresources.rb, lib/puppet_x/rustup/provider/collection/targets.rb, lib/puppet_x/rustup/provider/collection/toolchains.rb, manifests/init.pp, manifests/toolchain.pp
I think it will be easier to share code if all subresources call the name key in their hashes 'name'. This takes the first step toward that by modifying the toolchain hash.
This also clarifies a few variable names.
=> Use 'name' instead of 'toolchain' in toolchain hash

lib/puppet/type/rustup_internal.rb, lib/puppet_x/rustup/provider/collection/targets.rb, manifests/init.pp, manifests/target.pp
This finishes my switch to using a 'name' key in subresource hashes.
=> Use 'name' instead of 'target' in target hash

lib/puppet_x/rustup/property/subresources.rb
When a property changes on a resource, Puppet displays a change message with the old and new values. Previously, the value displayed as “old” was actually just the new values.
This fixes the problem.
It appears that Puppet may expect the collection object to be replaced rather than change.
Fixes #61 — Change messages for subresources don’t show old values
=> Fix old values for subresources in change display

lib/puppet/type/rustup_internal.rb
Each toolchain hash passed to `rustup_internal` should have three entries, not two. This fixes the documentation.
This also updates a few comments to be less editorial, since it turns out that `validate` working on entries in an array rather than the array itself is the intended behavior.
=> Fix documentation for rustup_internal.toolchains

lib/puppet_x/rustup/property/subresources.rb
Minor tweaks to documentation and variable naming to clarify that `is_to_s()` on a Subresource property works on multiple existing values.
=> Trivial: `is_to_s()` works on values (plural)

.github/workflows/pr-checks.yaml, metadata.json
Aside from Puppet-side changes, this fixes the PR Checks GitHub action so that it works with Puppet 8. Or something. I’m not really clear why it was failing, but this fixes it.
=> pdk update

CHANGELOG.md, lib/puppet/provider/rustup_internal/default.rb
This is the same as #81, just with commits to fix lints and add an entry in CHANGELOG.md.
=> Force native architecture for rustup bootstrap on MacOS (fix lints)

lib/puppet/provider/rustup_internal/default.rb
This is an attempt to fix or mitigate #80.
On MacOS, it runs the rustup bootstrap shell script via "arch -64", which is shorthand for "arch -arch $native_arch" on 64 bit systems (which is all Rust fully supports on MacOS at this time, I believe).
On all other systems it does nothing.
=> Force native architecture for rustup bootstrap on MacOS

.github/workflows/pr-checks.yaml, metadata.json, provision.yaml, spec/acceptance/user_spec.rb, spec/spec_helper_acceptance.rb, spec/spec_helper_acceptance_local.rb
This makes a bunch of updates, some of which actually come from my [PDK template](https://github.com/danielparks/pdk-templates/).
The big one is that it now runs acceptance tests in CI on the GitHub runners directly, rather than trying to spin up containers under Puppet Litmus.
Fixes #83 — Acceptance tests broken.
=> Run acceptance tests directly on GitHub runners

lib/puppet/provider/rustup_internal/default.rb
I made [a mistake](https://github.com/danielparks/puppet-rustup/issues/80#issuecomment-1948816447) in my [initial draft](https://github.com/danielparks/puppet-rustup/pull/81) of this PR and only tested on a customized `facter` environment that downcased `Darwin` (the standard Puppet OS-family fact value for MacOS) to `darwin` on my environment.
This PR rectifies that issue.
Sorry for the mistake!
=> Compare to appropriate OS string

.github/workflows/pr-checks.yaml, metadata.json, spec/spec_helper_acceptance.rb
* Don’t use a full matrix in acceptance tests. This will allow us to only test the latest Puppet version on other platforms to save time and energy.
* There’s no need to build the module or install it in acceptance tests; Puppet Litmus takes care of all of that.
* Run accceptance tests on Puppet 6.
* Support (but do not enable) macOS in acceptance tests.
* Update actions/checkout to v4.
* Disable PR checks on push because we don’t use caching, so PR cache isolation is not an issue for us.
* Make platforms configurable.
* Add basic macOS support (not enabled by default).
=> Simplify acceptance tests in CI

spec/acceptance/user_spec.rb
Use `PUPPET` as the heredoc for Puppet code instead of `END`.
=> PR Checks / Acceptance: change Puppet code heredoc

.github/workflows/pr-checks.yaml, .sync.yml, REFERENCE.md, manifests/global.pp, spec/acceptance/global_spec.rb, spec/acceptance/user_spec.rb, spec/spec_helper_acceptance_local.rb
- **Acceptance tests: macOS has no /etc/profile.d.**
- **Acceptance tests: macOS has no /usr/sbin/nologin.**
- **Acceptance tests: create groups before users (for macOS).**
- **Acceptance tests: macOS should already have gcc installed.**
- **Acceptance tests: support macOS Rust toolchains and targets.**
- **Acceptance tests: enable macOS 12.**
=> Acceptance tests: enable macOS 12

.github/workflows/pr-checks.yaml, .gitignore, .pdkignore, .rubocop.yml, .sync.yml, .vscode/extensions.json, CHANGELOG.md, Gemfile, metadata.json, spec/spec_helper.rb
For some reason CI fails on macOS 14 (see PR #91).
=> CI: Switch macOS runner to 13 instead of latest
